######################################################################
# Automatically generated by qmake (2.01a) Wed Oct 19 21:34:22 2011
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += \
    def.h \
    main.h \
    digger.h \
    drawing.h
SOURCES += \
    main.cpp \
    digger.cpp \
    drawing.cpp \
    game_data.cpp

RESOURCES += \
    main.qrc




