######################################################################
# Automatically generated by qmake (2.01a) Wed Oct 19 21:34:22 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += \
    window_main.h \
    def.h \
    graphicsview.h
SOURCES += \
    window_main.cpp \
    graphicsview.cpp \
    qt_main.cpp

RESOURCES += \
    main.qrc








